# Generated by Django 3.0.2 on 2021-03-10 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
